<?php

return [
    'vorname' => [
        // Schreibvarianten und historische Formen
        ['Andreas', 'Andrae', 'Andrä'],
        ['Anna', 'Anne', 'Anna Maria'],
        ['Anton', 'Antonius'],
        ['Bartholomaeus', 'Bartholomäus'],
        ['Caecilia', 'Caecilie', 'Cäcilia', 'Cäcilie', 'Zäzilia'],
        ['Clemens', 'Clemens', 'Klemens'],
        ['Cornelia', 'Cornelie', 'Cornelia'],
        ['Dominikus', 'Dominik'],
        ['Elisabeth', 'Elisabet', 'Elisabetta', 'Elisabethe'],
        ['Eva', 'Eua'],
        ['Franz', 'Franciscus', 'Frantz'],
        ['Georg', 'Jorg', 'Jörg'],
        ['Gertraud', 'Gertrud', 'Gertruda'],
        ['Helena', 'Helene'],
        ['Jakob', 'Jacob', 'Jakobus'],
        ['Johann', 'Johannes', 'Hannes'],
        ['Josef', 'Joseph', 'Josefus'],
        ['Karl', 'Carl', 'Carolus'],
        ['Kaspar', 'Caspar', 'Casper'],
        ['Katharina', 'Catharina', 'Catherina', 'Katherina', 'Katarina', 'Katerina'],
        ['Klara', 'Clara'],
        ['Kunigunde', 'Cunigunde'],
        ['Magdalena', 'Magdalene'],
        ['Margaretha', 'Margarete', 'Margreth', 'Margret'],
        ['Maria', 'Marie'],
        ['Mathias', 'Matthias'],
        ['Michael', 'Michel'],
        ['Parasceva', 'Parascheva'],
        ['Paul', 'Paulus'],
        ['Regina'],
        ['Sebastian', 'Sebast'],
        ['Simon', 'Siman'],
        ['Stefan', 'Stephan'],
        ['Ursula', 'Ursel'],
        ['Vitus', 'Veit'],
        ['Walburga', 'Walpurg', 'Walpurgis'],
    ],
    'nachname' => [
        // Umlaut- und Schreibvarianten
        ['Aßl', 'Assl'],
        ['Döllinger', 'Doellinger'],
        ['Flöidl', 'Floidl'],
        ['Fraßl', 'Frassl'],
        ['Föstlin', 'Foestlin'],
        ['Glütler', 'Gluetler'],
        ['Gschösser', 'Gschoesser'],
        ['Graßberger', 'Grassberger', 'Graschberger'],
        ['Hartl', 'Haertl', 'Haertel', 'Härtl'],
        ['Hösl', 'Hoesl'],
        ['Jünnersmann', 'Juennersmann'],
        ['Kliebenschädel', 'Kliebenschaedel'],
        ['Costenzer', 'Kostenzer'],
        ['Krämer', 'Kraemer'],
        ['Lärch', 'Laerch'],
        ['Lüster', 'Luester'],
        ['Maierfrähers', 'Maierfraehers'],
        ['Mißlinger', 'Misslinger'],
        ['Oelinger', 'Ölinger'],
        ['Prüner', 'Pruener'],
        ['Pücher', 'Puecher'],
        ['Rißbacher', 'Rissbacher'],
        ['Ruegg', 'Rüegg'],
        ['Säggl', 'Saeggl'],
        ['Säuer', 'Saeuer'],
        ['Weissbacher', 'Weißbacher', 'Weisbacher'],
        ['Schiessling', 'Schießling'],
        ['Spötzenstatter', 'Spoetzenstatter'],
        ['Stätter', 'Staetter'],
        ['Stätler', 'Staetler'],
        ['Stölzl', 'Stoelzl'],
        ['Weißbichler', 'Weissbichler', 'Weisbichler'],
    ],
];
